version: '3.8'

services:
  jade:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jade
    ports:
      - "3000:3000"
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - jade_network

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis_stack
    ports:
      - "6379:6379"
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASS}
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    restart: unless-stopped
    networks:
      - jade_network

volumes:
  redis_data:

networks:
  jade_network: