version: '3.8'

services:
  Jade:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Jade
    ports:
      - "3000:3000"
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - jade_network

  redis:
    image: redis/redis-stack:latest
    container_name: redis_stack
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - jade_network

volumes:
  redis_data:

networks:
  jade_network: